# Generated by Django 2.2 on 2019-04-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='gift_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift', to='example.GiftList'),
        ),
    ]
